export const FETCH_PROJECTS = "FETCH_PROJECTS"
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS"
export const FETCH_PROJECTS_ERROR = "FETCH_PROJECTS_ERROR"

export const FETCH_PROJECTS_DETAILS = "FETCH_PROJECTS_DETAILS"
export const FETCH_PROJECTS_DETAILS_SUCCESS = "FETCH_PROJECTS_DETAILS_SUCCESS"
export const FETCH_PROJECTS_DETAILS_ERROR = "FETCH_PROJECTS_DETAILS_ERROR"